Initial import of the galera reconciler
openstack-k8s-operators/mariadb-operator pull request #47
Opened 2022-12-12 07:53 UTC by dciabrin

Let the mariadb operator reconcile galera resources, and update the way it reconciles mariadbdatabases, based on whether mariadb or galera is currently in use in the cluster.

It is assumed that either mariadb or galera is instantiated, you can't run both at the same time and reconcile mariadbdatabases.

As the galera reconciler becomes more mature, we may want to deprecate the mariadb reconciler and only support galera, as it can be deployed as a 1-node statefulset.

2022-12-12 08:13 UTC, dciabrin commented
I'm proposing to move the galera reconciler in this repo rather than to keep it in the galera-operator repo.

The reason being that the `mariadbdatabase` reconciler is currently duplicated in the galera-operator codebase, as it is necessary to deploy the openstack services without deploying the mariadb-operator. Technically, the only difference between mariadb-operator and galera-operator is that the latter implements the galera reconcilier. So for transitioning to using galera only, it looks simpler in the long run to backport it in the mariadb-operator and deprecate galera-operator.

As a proof of concept, with this PR and a modified openstack-operator [1], one can decide to deploy a control plane with either a simple MariaDB or Galera as a backing database. With the accompanying modified install_yamls [2] one can replace mariadb with a 1-node galera by running:
```
DBSERVICE=galera make openstack_deploy
```

One can also deploy a 3-node galera cluster as the database service with:
```
DBSERVICE=galera REPLICAS=3 make openstack_deploy
```

[1] https://github.com/openstack-k8s-operators/openstack-operator/compare/master...dciabrin:openstack-operator:galera-reconciler
[2] https://github.com/openstack-k8s-operators/install_yamls/compare/master...dciabrin:install_yamls:galera-reconciler

2022-12-12 11:15 UTC, gibizer requested changes
> The reason being that the mariadbdatabase reconciler is currently duplicated in the galera-operator codebase, as it is necessary to deploy the openstack services without deploying the mariadb-operator. Technically, the only difference between mariadb-operator and galera-operator is that the latter implements the galera reconcilier. So for transitioning to using galera only, it looks simpler in the long run to backport it in the mariadb-operator and deprecate galera-operator.

Please note that the mariadb-operator was a stopgap solution until the galera-operator is implemented. And as so it might not be designed for the long run. So by re-using parts of it this way you inherit a bag of shortcuts from this prototype. Here is the list of limitations I know about the prototype, but there can be a lot more:
-  The database user cannot be influenced it is hardcoded to the name of the DB schema: #36 
- Even though the service operators [define a database password per service](https://github.com/openstack-k8s-operators/install_yamls/blob/951bab66cbc1b5297f12d5905f89d493a50b2bf2/scripts/gen-input-kustomize.sh#L55), the mariadb-operator [uses a global password for each service by not selecting for the service specific password](https://github.com/openstack-k8s-operators/mariadb-operator/blob/597b259525acc6cc36e3653abd9472bf9b91e617/pkg/database.go#L68)

Therefore I think it would be better not to bring this shortcuts forward but design something for the long run on the mariadbdatabase side too.

2022-12-12 13:20 UTC, stuggi commented
> > The reason being that the mariadbdatabase reconciler is currently duplicated in the galera-operator codebase, as it is necessary to deploy the openstack services without deploying the mariadb-operator. Technically, the only difference between mariadb-operator and galera-operator is that the latter implements the galera reconcilier. So for transitioning to using galera only, it looks simpler in the long run to backport it in the mariadb-operator and deprecate galera-operator.
> 
> Please note that the mariadb-operator was a stopgap solution until the galera-operator is implemented. And as so it might not be designed for the long run. So by re-using parts of it this way you inherit a bag of shortcuts from this prototype. Here is the list of limitations I know about the prototype, but there can be a lot more:
> 
> * The database user cannot be influenced it is hardcoded to the name of the DB schema: #36
> * Even though the service operators [define a database password per service](https://github.com/openstack-k8s-operators/install_yamls/blob/951bab66cbc1b5297f12d5905f89d493a50b2bf2/scripts/gen-input-kustomize.sh#L55), the mariadb-operator [uses a global password for each service by not selecting for the service specific password](https://github.com/openstack-k8s-operators/mariadb-operator/blob/597b259525acc6cc36e3653abd9472bf9b91e617/pkg/database.go#L68)
> 
> Therefore I think it would be better not to bring this shortcuts forward but design something for the long run on the mariadbdatabase side too.

I think the general functionality of mariadb-operator is something we still want to have, I mean the split in maraidb and mariadbdatabases. The mentioned limitations are valid and a must have feature/functionality. We only did not add this to mariadb-databases due to the galera development. While I think the two mentioned limitations are easy to be fixed/enhanced, I agree that if we see that there are disadvantages in the current architecture that we should change and break it now instead of a later time.

2022-12-13 14:30 UTC, abays commented on controllers/galera_controller.go
> +//+kubebuilder:rbac:groups="",resources=pods,verbs=list;get
Can these be combined into one RBAC annotation?

2023-01-05 10:51 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +	StorageClass string `json:"storageClass,omitempty"`
I updated them to be required for now, thanks for the feedback

2023-01-05 10:51 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{RequeueAfter: time.Second * 5}, err
Ack

2023-01-05 10:51 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{RequeueAfter: time.Second * 5}, err
Ack

2023-01-05 10:52 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{Requeue: true}, nil
Ack thanks

2023-01-05 10:53 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{}, nil
Ah right I overlooked it

2023-01-05 10:53 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{Requeue: true}, nil
ack

2023-01-05 10:54 UTC, dciabrin commented on controllers/galera_controller.go
> +				if pod.Status.Phase == corev1.PodRunning {
alright I split the nested loops

2023-01-05 10:55 UTC, dciabrin commented on controllers/galera_controller.go
> +		return ctrl.Result{RequeueAfter: time.Duration(5) * time.Second}, nil
I tried to follow a pattern "update a single thing at a time", but thinking about it now, it doesn't make much sense if we run a single update in the defer and if I can always recover this state whenever the update failed. I removed it. Thanks

2023-01-05 10:57 UTC, dciabrin commented on controllers/galera_controller.go
> +			return ctrl.Result{RequeueAfter: time.Duration(5) * time.Second}, nil
Done

2023-01-05 11:03 UTC, dciabrin commented on controllers/galera_controller.go
> +				return ctrl.Result{RequeueAfter: time.Duration(3) * time.Second}, nil
So I have tested and I think I still need this requeue because at this time, the pods at still in Init state, and they are not switching to ready until the controller has had a chance to probe all this info it needs from the pods. Requeuing allows me to see all pods in Running state (so prior the Ready state), which is the condition I need.

2023-01-05 11:04 UTC, dciabrin commented on controllers/galera_controller.go
> +			}
This is done on purpose to mimick what we have in current tripleo: the gcomm string is based on the Spec rather than the Status.

2023-01-05 11:04 UTC, dciabrin commented on controllers/galera_controller.go
> +	replicas := int(instance.Spec.Replicas)
see my comments above

2023-01-05 11:06 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +	// +kubebuilder:validation:Minimum=1
Done, got rid of omitempty and added the explicit enum cases (we support 1 and 3 for the time being).

2023-01-05 11:07 UTC, dciabrin commented on controllers/galera_controller.go
> +func execInPod(r *GaleraReconciler, namespace string, pod string, container string, cmd []string, fun func(*bytes.Buffer, *bytes.Buffer) error) error {
Ack, I refactored this function to not depend on the mariadb-operator if/when we want to move it to lib-common. Thanks

2023-01-05 11:07 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +	Secret string `json:"secret,omitempty"`
Ouch. Indeed, I moved it to be a required field

2023-01-05 11:09 UTC, dciabrin commented on controllers/galera_controller.go
> +		}
OK I am going to leave this Update() as I'm not sure there's a consensus yet. I got rid of all the other in favor of the defer function doing it in the end.

2023-01-05 11:10 UTC, dciabrin commented on controllers/galera_controller.go
> +	for node := range status.Attributes {
Done, thanks for the pointer.

2023-01-05 11:11 UTC, dciabrin commented on controllers/galera_controller.go
> +	uri := "gcomm://" + strings.Join(res, ",")
I don't think so because the gcomm doesn't use any special part in a URI.

2023-01-05 11:12 UTC, dciabrin commented on controllers/galera_controller.go
> +	op, err = controllerutil.CreateOrPatch(ctx, r.Client, headless, func() error {
Ack, thanks for the pointer I didn't realize how this was supposed to work

2023-01-05 11:12 UTC, dciabrin commented on controllers/galera_controller.go
> +	}
Done

2023-01-05 11:13 UTC, dciabrin commented on controllers/galera_controller.go
> +			AdditionalTemplate: map[string]string{
Oh good to know, thanks!

2023-01-05 11:13 UTC, dciabrin commented on pkg/utils.go
> +	return map[string]string{
Thanks for the pointer. Done

2023-01-05 11:13 UTC, dciabrin commented on controllers/galera_controller.go
> +//+kubebuilder:rbac:groups="",resources=pods,verbs=list;get
Right, done.

2023-01-05 11:14 UTC, dciabrin commented on controllers/galera_controller.go
> +					return ctrl.Result{Requeue: true}, nil
Ack.

2023-01-05 11:14 UTC, dciabrin commented on controllers/galera_controller.go
> +	op, err = controllerutil.CreateOrPatch(ctx, r.Client, service, func() error {
done

2023-01-05 11:15 UTC, dciabrin commented on templates/galera/bin/detect_gcomm_and_start.sh
> +
Makes sense. done

2023-01-05 11:18 UTC, dciabrin commented on templates/galera/bin/detect_last_commit.sh
> +
I'll add the set -eu on this one.

2023-01-05 11:18 UTC, dciabrin commented on templates/galera/bin/mysql_bootstrap.sh
> +set +x
Done

2023-01-05 11:18 UTC, dciabrin commented on templates/galera/bin/mysql_probe.sh
> +
Done

2023-01-05 13:47 UTC, dciabrin commented
Apologies for the late PR update, I had difficulties testing the new version with openstack-operator selectivitely enabling/disabling services..

2023-01-09 12:45 UTC, gibizer requested changes

2023-01-09 12:45 UTC, gibizer commented on api/v1beta1/galera_types.go
> +	StorageRequest string `json:"storageRequest"`
I think `// +kubebuilder:validation:Required` is missing from here

2023-01-09 12:45 UTC, gibizer commented on controllers/galera_controller.go
> +		}
[It is](https://github.com/openstack-k8s-operators/lib-common/pull/117) pretty close to land but not landed yet. So I agree to get back to this when the generic lib-common PatchInstance lands.

2023-01-09 12:45 UTC, gibizer commented on controllers/galera_controller.go
> +		err = r.Update(ctx, statefulset)
I think this Update is still unnecessary as it is already done at L215-L218:
```golang
	pkgsf := mariadb.StatefulSet(instance)
	statefulset := &appsv1.StatefulSet{ObjectMeta: pkgsf.ObjectMeta}
	op, err := controllerutil.CreateOrPatch(ctx, r.Client, statefulset, func() error {
		statefulset.Spec = pkgsf.Spec
```

2023-01-09 12:45 UTC, gibizer commented on controllers/galera_controller.go
> +			return ctrl.Result{RequeueAfter: time.Second * 5}, err
Do we need to polling? I don't see `Owns` for Endpoints set below so we cannot simply remove the requeue. But I'm wondering why we don't use Owns instead?

2023-01-09 12:45 UTC, gibizer commented on controllers/galera_controller.go
> +		// Spec updated - return and requeue
drop the comment or at least sync it with the change that requeue is removed.

2023-01-09 12:45 UTC, gibizer commented on controllers/galera_controller.go
> +				return ctrl.Result{RequeueAfter: time.Duration(3) * time.Second}, nil
It is strange. As far as I understand you need to get the galera_controller to run a Reconcile after the Pods are Ready. But I believe when a pod becomes Ready then the StatefulSet.ReadyReplicas is updated automatically by k8s and that should trigger a Reconcile run on the galera_controller as the controller Owns the StatefulSet. So in your test did the Pods become Ready without triggering the reconcile on galera_controller?

2023-01-10 12:09 UTC, dciabrin commented on controllers/galera_controller.go
> +		err = r.Update(ctx, statefulset)
Good catch, thank you.

2023-01-10 12:09 UTC, dciabrin commented on controllers/galera_controller.go
> +		// Spec updated - return and requeue
block removed

2023-01-11 07:44 UTC, stuggi commented on api/v1beta1/galera_types.go
> +// +kubebuilder:subresource:status
might want to add the following to show the status/massage of the overall condition on the cli 

```
//+kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.conditions[0].status",description="Status"
//+kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[0].message",description="Message"
```

2023-01-11 07:44 UTC, stuggi commented on controllers/galera_controller.go
> +		}
its merged now :) . check e.g. https://github.com/openstack-k8s-operators/glance-operator/pull/117 for using it.

2023-01-11 07:44 UTC, stuggi commented on controllers/galera_controller.go
> +		}
see https://github.com/openstack-k8s-operators/glance-operator/pull/117 for the changes to update the instance

2023-01-11 07:44 UTC, stuggi commented on controllers/galera_controller.go
> +	pkgsf := mariadb.StatefulSet(instance)
not a must, could also use https://github.com/openstack-k8s-operators/lib-common/blob/master/modules/common/statefulset/statefulset.go

2023-01-11 07:44 UTC, stuggi commented on controllers/galera_controller.go
> +		statefulset.Spec = pkgsf.Spec
the spec.selector can not be updated, so there should be a condition or another way to prevent it from being changed later. see https://github.com/openstack-k8s-operators/lib-common/blob/master/modules/common/statefulset/statefulset.go#L60-L62

2023-01-11 07:44 UTC, stuggi commented on controllers/galera_controller.go
> +	headless := &corev1.Service{ObjectMeta: pkghl.ObjectMeta}
we might want to extend https://github.com/openstack-k8s-operators/lib-common/blob/master/modules/common/service/service.go for headless service and use it later

2023-01-12 22:08 UTC, jistr commented on api/v1beta1/galera_types.go
> +	AdoptionRedirect AdoptionRedirectSpec `json:"adoptionRedirect"`
Based on the constraints introduced before EOY, it looks like we'll be merging Adoption and FFU into a combined procedure, which means it will be less gradual and more of a "big bang", and we will not make use of the AdoptionRedirect bit. I think we can still merge it as-is though, and remove the redirect functionality subsequently.

2023-01-18 08:08 UTC, dciabrin commented on controllers/galera_controller.go
> +			return ctrl.Result{RequeueAfter: time.Second * 5}, err
So I have update the reconcile strategy in the next version of the PR to support restarting failed pods and reconciling the galera state out of a running statefulset. I added the explanation as to why i need to requeue here.
The TL;DR is that 1) I needed to use SetControllerReference instead of SetOwnerReference to get all events from a statefulset; 2) I don't receive events when pod's state change, only when the statefulset's state changes (e.g.  availableReplicas).

2023-01-18 08:59 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +// +kubebuilder:subresource:status
Ack thanks.

2023-01-18 09:41 UTC, dciabrin commented on controllers/galera_controller.go
> +			return ctrl.Result{RequeueAfter: time.Second * 5}, err
Correct, that's just a bad copy from the mariadb controller. I changed the pattern to make it look like all the other CR instantiated by this controller.

2023-01-18 09:43 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +// +kubebuilder:subresource:status
@gibizer see my comments above as to why i need to requeue. It's detailed in the comments of the next revision

2023-01-18 09:43 UTC, dciabrin commented on controllers/galera_controller.go
> +		}
Thanks, I updated the defer function to use it.

2023-01-18 16:05 UTC, dciabrin commented on controllers/galera_controller.go
> +		statefulset.Spec = pkgsf.Spec
Alright lib-common's statefulset should now do that for me

2023-01-18 16:06 UTC, dciabrin commented on controllers/galera_controller.go
> +	headless := &corev1.Service{ObjectMeta: pkghl.ObjectMeta}
Let's discuss that after this PR?

2023-01-18 16:07 UTC, dciabrin commented on api/v1beta1/galera_types.go
> +	AdoptionRedirect AdoptionRedirectSpec `json:"adoptionRedirect"`
Ack, makes sense

2023-01-23 14:30 UTC, gibizer reviewed
I won't block this even though I still not fully get some of the polling here.

2023-01-23 14:30 UTC, gibizer commented on controllers/galera_controller.go
> +	}
I don't want to block on this and I'm probably missing something. But this condition `statefulset.Status.AvailableReplicas != statefulset.Status.Replicas` does not directly depends on the state of the Pod but only directly depends on the Status of the StatefulSet. So by assuming that the instance get reconciled for each StatefulSet.Status change (and not for the Pod changes) then instead of polling for the condition `statefulset.Status.AvailableReplicas == statefulset.Status.Replicas` we can simply wait for that condition to happen. When that happen there will be a reconcile call on this instance as the condition can only happen by a change on `statefulset.Status`

2023-02-01 14:18 UTC, dciabrin commented on controllers/galera_controller.go
> +	}
If I understood correctly, the point of this remark is "it's not necessary to requeue when the condition is false because eventually the statefulset will have all pods available and retrigger an event for that".

I think the misunderstanding here is the constraint around pod's availability vs galera bootstrap. A pod becomes available IFF galera has been started on it (when the pod starts, it's in a wait loop initially). And galera is not started on a pod until all pods have had a chance to get introspected for determining the last seqno. And this last constraint is why I require a requeue here. The statefulset's status doesn't change when its pods's main container becomes running. So The galera controller may miss the occasion of polling all pods without requeuing. If so, bootstrap would not finish, no galera would get started, and the statefulset.status.availablereplicas would never increase.

2023-02-01 17:38 UTC, gibizer commented on controllers/galera_controller.go
> +	}
Thank you for explaining it. I think I see now. So the operator needs to manipulate the pods that are started but not ready yet to allow them to transition to ready eventually. Therefore the operator cannot simply wait for the Pods to become ready and the StatefulSet.AailableReplicas to increase.

2023-02-02 11:13 UTC, dciabrin commented on controllers/galera_controller.go
> +	}
That's exactly that.

2023-02-02 13:46 UTC, dciabrin commented on controllers/galera_controller.go
> +		}
done thanks

2023-02-06 09:52 UTC, stuggi commented on .gitignore
> +!templates/galera/bin
could  just ignore /bin . could do in a follow up

2023-02-06 09:52 UTC, stuggi commented on api/bases/mariadb.openstack.org_galeras.yaml
> +    controller-gen.kubebuilder.io/version: v0.9.2
requires rebase. with update of golang, sdk + controller-tools version its now 0.10.0 . https://github.com/openstack-k8s-operators/mariadb-operator/blob/master/Makefile#L182

2023-02-06 09:52 UTC, stuggi commented on pkg/statefulset.go
> +			PodManagementPolicy: "Parallel",
should use const appsv1.ParallelPodManagement https://pkg.go.dev/k8s.io/api/apps/v1#PodManagementPolicyType

2023-02-07 13:40 UTC, dciabrin commented on .gitignore
> +!templates/galera/bin
Ah alright. Done

2023-02-08 17:53 UTC, dciabrin commented on api/bases/mariadb.openstack.org_galeras.yaml
> +    controller-gen.kubebuilder.io/version: v0.9.2
Ack, done

2023-02-08 17:53 UTC, dciabrin commented on pkg/statefulset.go
> +			PodManagementPolicy: "Parallel",
Done

2023-02-09 09:20 UTC, gibizer approved these changes
This still look OK to me and as I see @stuggi's comment were fixed. So lets merge this.

2023-02-13 10:46 UTC, stuggi approved these changes
/lgtm

2023-02-13 10:50 UTC, merged