Finalizers for MariaDBDatabase
openstack-k8s-operators/mariadb-operator pull request #69
Opened 2023-02-13 10:49 UTC by abays

Does two things:

1. Adds a self-finalizer to the `MariaDBDatabase` CR.
2. When a `MariaDBDatabase` CR is created, we now add a finalizer to the associated `Galera` or `MariaDB` to prevent accidental deletion of the latter.  We also remove the finalizer from the `Galera` or `MariaDB` when the `MariaDBDatabase` is deleted.

2023-02-13 14:39 UTC, gibizer requested changes

2023-02-13 14:39 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
>  	}
I think the finalizer logic is correct but I'd like to simplify this finalizer implementation a bit.

```golang
db, err := GetDB(...) // get the MariaDB or Galera CR as proposed

// if we are being deleted then we have to remove the finalizer from MariaDB/Galera and then remove it from ourselves
if !instance.DeletionTimestamp.IsZero() {
    if err != nil {  // so we have MariaDB or Galera to remove finalizer from
        if controllerutil.RemoveFinalizer(db, fmt.Sprintf("%s-%s", helper.GetFinalizer(), instance.Name)) {
            err := r.Update(ctx, db)
            if err != nil {
                return ctrl.Result{}, err
            }
        }    
    }
    
    // all our external cleanup logic is done so we can remove our own finalizer to signal that we can be deleted.
    controllerutil.RemoveFinalizer(instance, helper.GetFinalizer())
    // we can unconditionally return here as this is basically the end of the delete sequence for MariaDBDatabase
    // so nothing else needs to be done in the reconcile.
    return ctrl.Result{}, nil
}

// we now that this is not a delete case

if k8s_errors.IsNotFound(err) {
        // as it is not a delete case we need to wait for MariaDB or Galera to exists before we can continue.
	return ctrl.Result{RequeueAfter: time.Duration(10) * time.Second}, nil
}

// here we know that MariaDB or Galera exists so add a finalizer to ourselves and to the db CR. Before this point there is no reason to have a finalizer on ourselves as nothing to cleanup.

if instance.DeletionTimestamp.IsZero() {    // this condition can be removed if you wish as it is always true at this point otherwise we would returned earlier.
    if controllerutil.AddFinalizer(db, fmt.Sprintf("%s-%s", helper.GetFinalizer(), instance.Name)) {
        err := r.Update(ctx, db)
        if err != nil {
            return ctrl.Result{}, err
        }
    }

    if controllerutil.AddFinalizer(instance, helper.GetFinalizer()) {
        // we need to persist this right away
        return ctrl.Result{}, nil
    }
}

// we can do our normal flow
```
On positive thing of this code that it has clearer separation between the delete and the non delete codepath. I can even suggest to pull a function out for the delete path to further separate them.

2023-02-13 14:39 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
>  		return ctrl.Result{RequeueAfter: time.Duration(10) * time.Second}, nil
I think we can end up here when no MariaDB or Galera exists and MariaDBDatabase is being deleted. I'm not sure what will happen if we requeue here. Will this be an infinite requeue as we never responded that it is OK to be deleted? Or as soons as the finalizer is removed from ourselves the framework deletes the CR and stops reconciling?

2023-02-13 14:45 UTC, abays commented on controllers/mariadbdatabase_controller.go
>  		return ctrl.Result{RequeueAfter: time.Duration(10) * time.Second}, nil
Since `!instance.DeletionTimestamp.IsZero()`, k8s is thus trying to delete the instance but can't yet due to the finalizer.  So once we remove the finalizer, k8s will continue to delete the instance.

2023-02-13 14:48 UTC, abays commented on controllers/mariadbdatabase_controller.go
> +		// being deleted but Galera/MariaDB is not found
It shouldn't be a common execution path by any means.  But someone could, for instance, delete the `MariaDB` instance and then manually remove the finalizer (via `oc edit` or whatever), and then you'd be in this situation.

2023-02-13 14:57 UTC, abays commented on controllers/mariadbdatabase_controller.go
>  	}
Sure, I can refactor it like this

2023-02-13 14:58 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
>  		return ctrl.Result{RequeueAfter: time.Duration(10) * time.Second}, nil
OK, so it CR will be deleted even if there a reconcile is requeued for it.

2023-02-13 15:02 UTC, abays commented on controllers/mariadbdatabase_controller.go
>  		return ctrl.Result{RequeueAfter: time.Duration(10) * time.Second}, nil
I will test it again to make sure my understanding is correct, but I'm pretty sure it's fine

2023-02-13 15:18 UTC, abays commented on controllers/mariadbdatabase_controller.go
>  	}
Actually, it can't be quite as simple as this.  The "normal flow" needs two additional things:

1. Some way of indicating that either `Galera` or `MariaDB` is being processed
2. The actual `Galera` or `MariaDB` object

So perhaps the return of the proposed `GetDB()` func can return more than just `client.Object` and `error`.  I'll look into it.

2023-02-13 15:22 UTC, stuggi commented on controllers/mariadbdatabase_controller.go
> +	if instance.DeletionTimestamp.IsZero() && controllerutil.AddFinalizer(db, fmt.Sprintf("%s-%s", helper.GetFinalizer(), instance.Name)) {
should the finalizer always be more specific then just the `gvk.Kind`? https://github.com/openstack-k8s-operators/lib-common/blob/master/modules/common/helper/helper.go#L75 could be changed to have this format per default.

2023-02-13 15:30 UTC, abays commented on controllers/mariadbdatabase_controller.go
> +	if instance.DeletionTimestamp.IsZero() && controllerutil.AddFinalizer(db, fmt.Sprintf("%s-%s", helper.GetFinalizer(), instance.Name)) {
I suppose we could do that.  In this case it's not a "self-finalizer" though, but a finalizer placed on another object.  But we could always use a more nuanced finalizer no matter what the target.

2023-02-13 17:29 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
>  	}
ahh you are right. I ignored the details of GetDB. But adding GetDB wasn't my main point anyway. So I'm OK to keep that inline.

2023-02-13 17:33 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
> +	if instance.DeletionTimestamp.IsZero() && controllerutil.AddFinalizer(db, fmt.Sprintf("%s-%s", helper.GetFinalizer(), instance.Name)) {
For self-finalizer kind probably works. But it does not hurt to be more specific there either. So I'm totally OK to change the default finalizer name to <kind>-<name> format. So the result of h.GetFinalizer() can always be used by the instance as a finalizer on itself or on any other type.

2023-02-14 09:42 UTC, gibizer reviewed
one cleanup and then I think ti is good to go

2023-02-14 09:42 UTC, gibizer commented on controllers/mariadbdatabase_controller.go
> +		return ctrl.Result{}, nil
you can drop this as L153 already handles it

2023-02-14 09:52 UTC, abays commented on controllers/mariadbdatabase_controller.go
> +		return ctrl.Result{}, nil
Ack

2023-02-14 10:05 UTC, gibizer approved these changes
Looks good. Thanks @abays

2023-02-14 10:08 UTC, merged